version: '3'
services:
  mongodb:
    container_name: mongo-container
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - ./mongodata/:/usr/src/target-api/mongodata/

  api:
    container_name: api-container
    image: python:3.10-alpine
    working_dir: /usr/src/target-api
    command: sh -c "pip3 install -r requirements.txt && python3 -m src.server"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/target_api
      - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - "5000:5000"
    volumes:
      - ./src/:/usr/src/target-api/src/
      - ./requirements.txt:/usr/src/target-api/requirements.txt
    depends_on:
      - mongodb
      - elasticsearch
    
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      
    ports:
      - 9200:9200